document.writeln("<!-- Javascript -->");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/bootstrap.min.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/owl.carousel.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/jquery.flexslider-min.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/jquery.magnific-popup.min.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/jquery.sticky.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/jquery.easing.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/parallax.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/imagesloaded.min.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/jquery.isotope.min.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/jquery-waypoints.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/jquery.cookie.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/main.js\'></script>");
document.writeln("");
document.writeln("    <!-- Revolution Slider -->");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/jquery.themepunch.tools.min.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/jquery.themepunch.revolution.min.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/slider.js\'></script>");
document.writeln("    <!-- 自定义 -->");
document.writeln("<script src=\'javascript/indexVue.js\'></script>");
document.writeln("<script src=\'javascript/aboutVue.js\'></script>");