document.writeln("<!-- Basic Page Needs -->");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <!--[if IE]><meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge,chrome=1\'><![endif]-->");
document.writeln("    <title>Home</title>");
document.writeln("");
document.writeln("    <meta name=\'author\' content=\'llanc.cn\'>");
document.writeln("");
document.writeln("    <!-- Mobile Specific Metas -->");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1, maximum-scale=1\'>");
document.writeln("");
document.writeln("    <!-- Bootstrap  -->");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'stylesheets/bootstrap.css\'>");
document.writeln("");
document.writeln("<!-- Element组件样式 -->");
document.writeln("<link rel=\'stylesheet\' href=\'https://unpkg.com/element-ui/lib/theme-chalk/index.css\'>");
document.writeln("");
document.writeln("    <!-- Theme Style -->");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'stylesheets/style.css\'>");
document.writeln("");
document.writeln("    <!-- Responsive -->");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'stylesheets/responsive.css\'>");
document.writeln("");
document.writeln("    <!-- Colors -->");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'stylesheets/colors/color1.css\' id=\'colors\'>");
document.writeln("");
document.writeln("    <!-- Favicon and touch icons  -->");
document.writeln("    <link href=\'icon/apple-touch-icon-48-precomposed.png\' rel=\'apple-touch-icon-precomposed\' sizes=\'48x48\'>");
document.writeln("    <link href=\'icon/apple-touch-icon-32-precomposed.png\' rel=\'apple-touch-icon-precomposed\'>");
document.writeln("");
document.writeln("    <!--[if lt IE 9]>");
document.writeln("        <script src=\'javascript/html5shiv.js\'></script>");
document.writeln("        <script src=\'javascript/respond.min.js\'></script>");
document.writeln("    <![endif]-->");
document.writeln("<script src=\'https://cdn.jsdelivr.net/npm/vue/dist/vue.js\'></script>");
document.writeln("<script src=\'https://unpkg.com/axios/dist/axios.min.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'javascript/jquery.min.js\'></script>");
document.writeln("<!-- Element组件库 -->");
document.writeln("<script src=\'https://unpkg.com/element-ui/lib/index.js\'></script>");
document.writeln("<script>");
document.writeln("        $(function () {");
document.writeln("            $(\'#site-header\').load(\'header.html\');");
document.writeln("            $(\'#footer\').load(\'footer.html\');");
document.writeln("        });");
document.writeln("    </script>");
